### ISSUE TITLE
requirements.txt

### ISSUE THREAD

**Issue by XinGao18** [xkLi-Allen/MEGU#1]
作者你好，请问您可以使用'pip install -r requirements.txt'命令行重新编码一下该文件吗？您的现有文件中出现的是这种情况：
certifi @ file:///croot/certifi_1683875369620/work/certifi
cffi @ file:///tmp/abs_98z5h56wf8/croots/recipe/cffi_1659598650955/work
charset-normalizer @ file:///tmp/build/80754af9/charset-normalizer_1630003229654/work
感谢。

**Comment by xkLi-Allen** [comment]
你好，因为机器环境变动暂时无法 copy 原有虚拟环境，你可以尝试仅安装重要的 library 例如 pytorch 和 pyg，剩下的依赖视需求而定

**Comment by upstream-wb** [comment]
> 作者你好，请问您可以使用'pip install -r requirements.txt'命令行重新编码一下该文件吗？您的现有文件中出现的是这种情况： certifi @ file:///croot/certifi_1683875369620/work/certifi cffi @ file:///tmp/abs_98z5h56wf8/croots/recipe/cffi_1659598650955/work charset-normalizer @ file:///tmp/build/80754af9/charset-normalizer_1630003229654/work 感谢。

>您好，我在复现论文时也遇到了同样的问题，请问您解决这个问题了吗，可以请教一下解决方法吗？

**Comment by upstream-wb** [comment]
> 作者你好，请问您可以使用'pip install -r requirements.txt'命令行重新编码一下该文件吗？您的现有文件中出现的是这种情况： certifi @ file:///croot/certifi_1683875369620/work/certifi cffi @ file:///tmp/abs_98z5h56wf8/croots/recipe/cffi_1659598650955/work charset-normalizer @ file:///tmp/build/80754af9/charset-normalizer_1630003229654/work 感谢。
